import CommonButton from "@/component/CommonBtn/CommonBtn";
import { Company } from "@/component/Company/Company";
import Footer from "@/component/Footer/Footer";
import Header from "@/component/Header/Header";
import Heading from "@/component/Heading/Heading";
import ServicesSection from "@/component/ServicesSection/ServicesSection";
import StatCircle from "@/component/StatCircle/StatCircle";
import Subtitle from "@/component/Subtitle/Subtitlle";
import styles from "@/styles/About.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export default function About() {
  return (
    <>
      <Head>
        <title>Diama Technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ====== About Us Section ====== */}
      <section
        className={styles.section}
        style={{ backgroundImage: "url(/images/bannerBg.png)" }}
      >
        <div className="container">
          {/* Left Text Content */}
          <div className={styles.textBlock} data-aos="fade-up">
            <div className={styles.leftItem}>
              <Subtitle text={"About Us"} />
              <h1>
                Driven by Creativity
                <span className={styles.orange}> Powered by Technology</span>
              </h1>
            </div>
            <div className={styles.circleWrapper}>
              <svg
                viewBox="0 0 200 200"
                width="140"
                height="140"
                className={styles.circleSvg}
              >
                <defs>
                  <path
                    id="circlePath"
                    d="M 100, 100 m -75, 0 a 75,75 0 1,1 150,0 a 75,75 0 1,1 -150,0"
                  />
                </defs>
                <text
                  fill="#aaa"
                  fontSize="13"
                  fontWeight="500"
                  letterSpacing="3"
                >
                  <textPath xlinkHref="#circlePath" startOffset="0%">
                    • SCHEDULE A MEETING NOW • EXPLORE SOLUTIONS
                  </textPath>
                </text>
              </svg>

              <div className={styles.circleCenter}>
                LET’S <br /> GO
              </div>
            </div>
          </div>

          {/* Right Image + Circle */}
          <div className={styles.imageBlock} data-aos="fade-up">
            <div className={styles.subBlock}>
              <h3 className={styles.subHeading}>SmartPlatform Integration</h3>
              <p className={styles.subText}>
                Integrating platforms smartly so your business runs faster,
                smoother, and smarter. Empowering you with seamless connectivity
                and future-ready solutions.
              </p>
            </div>
            <img
              data-aos="zoom-in"
              src="/images/team-collaboration.png"
              alt="Team Collaboration"
              className={styles.mainImage}
            />
          </div>
        </div>
      </section>
      {/* ====== Solution Section ====== */}
      <section className={styles.section}>
        <div className="container">
          <div className={styles.solutionWrapper}>
            {/* Left Image */}
            <div className={styles.leftImage} data-aos="fade-right">
              <img src="/images/office-building.png" alt="Office Building" />
            </div>

            {/* Middle Content */}
            <div className={styles.content} data-aos="fade-left">
              <Subtitle text={"Not Just a Company, A Mindset"} />
              <Heading
                mainText={"Turning imagination into"}
                highlightText={"powerful solutions."}
              />

              <p>
                We are a team of passionate innovators, designers, and
                developers dedicated to building digital experiences that make a
                real difference. With creativity at our core and technology as
                our tool, we help businesses grow, adapt, and thrive in
                today&apos;s fast-changing digital world.
              </p>
              <div className={styles.bottomTextPart}>
                <div className={styles.bottomTextLeftPart}>
                  <p>
                    <strong>Our Mission →</strong> To empower brands and
                    businesses through innovative solutions in Digital
                    Marketing, Development, and UI/UX Design, ensuring
                    measurable growth and long-term success.
                  </p>

                  <p>
                    <strong>Our Vision →</strong> To become a global leader in
                    digital innovation, creating transformative solutions that
                    empower businesses, inspire creativity, and shape a smarter,
                    connected future.
                  </p>
                </div>
                <div className={styles.rightImage}>
                  <img src="/images/team.png" alt="Teamwork" />
                </div>
              </div>
            </div>

            {/* Right Image */}
          </div>
        </div>
      </section>
      <Company />
      <ServicesSection />

      {/* ====== Solution Section For Stats====== */}
      <section className={styles.statsSection}>
        <div className="container">
          {/* Main Section with 4 Overlapping Columns */}
          <div className={styles.mainSection}>
            {/* Column 1 */}
            <div className={styles.column}>
              {/* <div className={styles.statNumber}>100+</div> */}
              <StatCircle 
                endValue={100}
                suffix="+"
                lines={["Satisfied", "Clients"]}
              />

              <div className={styles.leftContent}>
                <p className={styles.freeConsultation}>
                  Free consultation for you
                </p>
                <h2>We are here to help any stage</h2>
              </div>
              <div className={styles.stageCard} data-aos="fade-up">
                <div className={styles.stageHeader}>
                  <h4>Early Stage</h4>
                </div>
                <p>Get to elevate your business with big-tech IT technology</p>
                <button className={styles.knowMoreBtn}>
                  Know More <span>→</span>
                </button>
              </div>
            </div>

            {/* Column 2 - Highlighted */}
            <div className={`${styles.column}`}>
              <StatCircle
                endValue={5000}
                suffix="+"
                lines={["Successful", "Projects Delivered"]}
              />

              <div className={styles.stageCard} data-aos="fade-up">
                <div className={styles.stageHeader}>
                  <h4>Growth Stage</h4>
                </div>
                <p>
                  Get to elevate your business with top-notch IT technology and
                  enter the world
                </p>
                <button className={styles.knowMoreBtn}>
                  Know More <span>→</span>
                </button>
              </div>
            </div>

            {/* Column 3 */}
            <div className={styles.column}>
              <StatCircle
                endValue={10}
                suffix="+"
                lines={["Ongoing", "Projects"]}
              />
              <div className={styles.stageCard} data-aos="fade-up">
                <div className={styles.stageHeader}>
                  <h4>Advance Stage</h4>
                </div>
                <p>
                  Get to elevate your business with top-notch IT technology and
                  deployment
                </p>
                <button className={styles.knowMoreBtn}>
                  Know More <span>→</span>
                </button>
              </div>
            </div>

            {/* Column 4 */}
            <div className={styles.column}>
              <StatCircle
                endValue={2}
                suffix=""
                lines={["Awards", "achievement"]}
              />
              <div className={styles.stageCard} data-aos="fade-up">
                <div className={styles.stageHeader}>
                  <h4>Final Stage</h4>
                </div>
                <p>Get to elevate your business with top-notch</p>
                <button className={styles.knowMoreBtn}>
                  Know More <span>→</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
