import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Articles.module.css";
import Header from "@/component/Header/Header";
import Subtitle from "@/component/Subtitle/Subtitlle";
import Link from "next/link";
import CommonButton from "@/component/CommonBtn/CommonBtn";
import Heading from "@/component/Heading/Heading";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper/modules";
import {
  HiOutlineArrowSmLeft,
  HiOutlineArrowSmRight,
  HiStar,
} from "react-icons/hi";
import { useRef, useState } from "react";
import { BiSolidQuoteAltLeft, BiSolidQuoteAltRight } from "react-icons/bi";
import Portfolio from "@/component/Portfolio/Portfolio";
import Footer from "@/component/Footer/Footer";
import Counter from "@/component/Counter/Counter";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export default function Service() {
  const [activeTab, setActiveTab] = useState(0);
  const swiperRef = useRef(null);
  const tabs = [
    "All",
    "Politics",
    "Skill Acquisition",
    "Education",
    "Sport",
    "Business",
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ======Banner======= */}
      <section
        className={styles.mainBanner}
        style={{ backgroundImage: "url(/images/bannerBg.png)" }}
      >
        <div className="container">
          <div className={styles.bannerContent}>
            <div className={styles.bannerLeftContent}>
              <Subtitle text={"Stay inspired. Stay ahead."} />
              <h1>
                Crafting Experiences That <span> Make an Impact</span>
              </h1>
            </div>
          </div>
        </div>
      </section>

      {/* ======technology====== */}
      <section className={styles.portfolio}>
        <div className="container">
          <div
            className={styles.serviceWrap}
            // style={{ backgroundImage: "url('/images/serviceBg.jpg')" }}
          >
            <div className={styles.blogTop}>
              <div className={styles.blogTopHeader}>
                <h3>News and Blog</h3>
                <p>
                  Your go-to source for company news, industry insights, and
                  creative ideas.
                </p>
              </div>
              <div className={styles.blogTab}>
                <ul className={styles.portfolioTab}>
                  {tabs.map((tab, index) => (
                    <li
                      key={index}
                      className={activeTab === index ? styles.active : ""}
                      onClick={() => setActiveTab(index)}
                    >
                      {tab}
                    </li>
                  ))}
                </ul>
                 <div className={styles.blogTabContent}>
                    
                 </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ========Companies======= */}
      <section className={styles.companies}>
        <div className="container">
          <Subtitle text={"Trusted by over 50,000 companies of all sizes"} />
          <div className={styles.companyWrap}>
            <ul>
              <li>
                <img src={"/images/segement.png"} alt="segemnt" />
              </li>
              <li>
                <img src={"/images/asana.png"} alt="asana" />
              </li>
              <li>
                <img src={"/images/intercom.png"} alt="intercom" />
              </li>
              <li>
                <img src={"/images/zenefits.png"} alt="zenefits" />
              </li>
              <li>
                <img src={"/images/greenhouse.png"} alt="greenhouse" />
              </li>
              <li>
                <img src={"/images/chargebee.png"} alt="chargebee" />
              </li>
              <li>
                <img src={"/images/lattice.png"} alt="lattice" />
              </li>
              <li>
                <img src={"/images/frame.png"} alt="frame" />
              </li>
              <li>
                <img src={"/images/mutiny.png"} alt="mutiny" />
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ========build====== */}
      <section
        className={styles.buildTogether}
        style={{ backgroundImage: "url(/images/buildBg.png)" }}
      >
        <img
          src={"/images/Union.png"}
          alt="segemnt"
          className={styles.buildshape}
        />
        <div className="container">
          <div className={styles.buildTogetherContent}>
            <Heading
              mainText={"Let’s Build the Future Together"}
              className={styles.buildTogetherHeading}
            />
            <p>
              Ready to transform your ideas into reality? Let’s collaborate and
              craft solutions that drive success.
            </p>
            <CommonButton text={"Let’s Work Together"} />
          </div>
        </div>
      </section>

      {/* ------footer-------- */}
      <Footer />
    </>
  );
}
