import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/component/Header/Header";
import Subtitle from "@/component/Subtitle/Subtitlle";
import Link from "next/link";
import CommonButton from "@/component/CommonBtn/CommonBtn";
import Heading from "@/component/Heading/Heading";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper/modules";
import {
  HiOutlineArrowSmLeft,
  HiOutlineArrowSmRight,
  HiStar,
} from "react-icons/hi";
import { useRef } from "react";
const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export default function Home() {
  const swiperRef = useRef(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ======Banner======= */}
      <section className={styles.mainBanner}>
        <div className="container">
          <div className={styles.bannerContent}>
            <Subtitle
              text={"Unlock Limitless Possibilities in the Digital Era"}
            />
            <h1>
              From strategy to execution, we fuel your journey with{" "}
              <span> creativity, technology, and excellence.</span>
            </h1>
            <CommonButton text="Our Services" href="/services" />
          </div>
          <div className={styles.bannerImage}>
            <img src={"/images/banner-image.png"} alt="banner image" />
          </div>
        </div>
        <div className={styles.shape}>
          <img src={"/images/bannerShape.png"} alt="shape" />
        </div>
      </section>

      {/* ========Companies======= */}
      <section className={styles.companies}>
        <div className="container">
          <Subtitle text={"Trusted by over 50,000 companies of all sizes"} />
          <div className={styles.companyWrap}>
            <ul>
              <li>
                <img src={"/images/segement.png"} alt="segemnt" />
              </li>
              <li>
                <img src={"/images/asana.png"} alt="asana" />
              </li>
              <li>
                <img src={"/images/intercom.png"} alt="intercom" />
              </li>
              <li>
                <img src={"/images/zenefits.png"} alt="zenefits" />
              </li>
              <li>
                <img src={"/images/greenhouse.png"} alt="greenhouse" />
              </li>
              <li>
                <img src={"/images/chargebee.png"} alt="chargebee" />
              </li>
              <li>
                <img src={"/images/lattice.png"} alt="lattice" />
              </li>
              <li>
                <img src={"/images/frame.png"} alt="frame" />
              </li>
              <li>
                <img src={"/images/mutiny.png"} alt="mutiny" />
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ======vision and mission====== */}
      <section className={styles.visionMission}>
        <div className="container">
          <div className={`${styles.row} row`}>
            <div className="col-lg-6">
              <div className={styles.visionImage}>
                <img src={"/images/vision.png"} alt="vision" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.visionContent}>
                <Subtitle text={"Our Vison"} />
                <p>
                  To become a global leader in digital innovation by creating
                  transformative solutions that empower businesses, inspire
                  creativity, and shape a smarter, connected future.
                </p>
                <span className={styles.visionPoint}>Key vison point:</span>
                <ul>
                  <li>
                    Empower Businesses → Driving sustainable growth and success
                    through digital transformation.
                  </li>
                  <li>
                    Inspire Creativity → Fostering innovation and imaginative
                    solutions that make a difference.
                  </li>
                  <li>
                    Shape a Smarter, Connected Future → Building
                    technology-driven ecosystems that connect people, ideas, and
                    opportunities globally.
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className={`${styles.row} row`}>
            <div className="col-lg-6">
              <div className={styles.visionImage}>
                <img src={"/images/mission.png"} alt="vision" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.visionContent}>
                <Subtitle text={"Our Mission"} />
                <p>
                  Our mission is to bridge technology and creativity to deliver
                  impactful digital experiences. We are committed to driving
                  growth through innovation, building trust through
                  transparency, and creating long-lasting value for our clients
                  by turning bold ideas into powerful realities.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.missionShape}>
          <img src={"/images/shape-2.png"} alt="shape" />
        </div>
      </section>

      {/* =====popular services====== */}
      <section className={styles.popularServices}>
        <div className="container">
          <div className={styles.topHeading}>
            <Subtitle text={"Solutions That Drive Success"} />
            <Heading mainText={"Popular"} highlightText={"Services"} />
            <p>
              Smart, innovative, and result-driven services built to grow your
              business.
            </p>
          </div>
          <div
            className={styles.serviceWrap}
            // style={{ backgroundImage: "url('/images/serviceBg.jpg')" }}
          >
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Digital Marketing</Link>
                </h5>
                <p>Elevate Your Brand with Strategic Digital Marketing.</p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>UI/UX Design</Link>
                </h5>
                <p>
                  Designing intuitive, user-friendly, and visually stunning
                  experiences that keep customers engaged and satisfied.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Graphic Design</Link>
                </h5>
                <p>Elevate Your Brand with Strategic Digital Marketing.</p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Web Design & Devlopment</Link>
                </h5>
                <p>Elevate Your Brand with Strategic Digital Marketing.</p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>

            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>App Development </Link>
                </h5>
                <p>Elevate Your Brand with Strategic Digital Marketing.</p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>DevOps</Link>
                </h5>
                <p>Elevate Your Brand with Strategic Digital Marketing.</p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ======testimonial========= */}
      <section className={styles.testimonial}>
        <div className="container">
          <div className={styles.topHeading}>
            <Subtitle text={"Testimonial"} />
            <Heading
              mainText={"What our customer"}
              highlightText={"says About Us"}
            />
          </div>
          <div
            className={styles.testimonialSlider}
            style={{ backgroundImage: "url('/images/testiBg.png')" }}
          >
            <Swiper
              modules={[Navigation, Autoplay]}
              spaceBetween={30}
              slidesPerView={1}
              onSwiper={(swiper) => (swiperRef.current = swiper)}
              pagination={false}
              autoplay={{ delay: 3000 }}
              loop={true}
            >
              <SwiperSlide>
                <div className={styles.slideItem}>
                  <p>
                    We were invisible on Google before partnering with DIAMA
                    Technologies. Within just three months, our website ranked
                    on the first page for our primary keywords. Their SEO team
                    knows exactly what they’re doing."
                  </p>
                  <ul>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                  </ul>
                  <h4>Rajesh Mehra</h4>
                  <span>Founder</span>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.slideItem}>
                  <p>
                    We were invisible on Google before partnering with DIAMA
                    Technologies. Within just three months, our website ranked
                    on the first page for our primary keywords. Their SEO team
                    knows exactly what they’re doing."
                  </p>
                  <ul>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                  </ul>
                  <h4>Rajesh Mehra</h4>
                  <span>Founder</span>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.slideItem}>
                  <p>
                    We were invisible on Google before partnering with DIAMA
                    Technologies. Within just three months, our website ranked
                    on the first page for our primary keywords. Their SEO team
                    knows exactly what they’re doing."
                  </p>
                  <ul>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                    <li>
                      <HiStar />
                    </li>
                  </ul>
                  <h4>Rajesh Mehra</h4>
                  <span>Founder</span>
                </div>
              </SwiperSlide>
            </Swiper>
            <div className={styles.navigationWrap}>
              <button
                onClick={() => {
                  swiperRef.current.slidePrev();
                  console.log("Prev button clicked");
                }}
                className={styles.customPrev}
              >
                <HiOutlineArrowSmLeft /> 
              </button>
              <button
                onClick={() => {
                  swiperRef.current.slideNext();
                  console.log("Next button clicked");
                }}
                className={styles.customNext}
              >
                <HiOutlineArrowSmRight />
              </button>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
