import CommonButton from "@/component/CommonBtn/CommonBtn";
import Counter from "@/component/Counter/Counter";
import Footer from "@/component/Footer/Footer";
import Header from "@/component/Header/Header";
import Heading from "@/component/Heading/Heading";
import Portfolio from "@/component/Portfolio/Portfolio";
import Subtitle from "@/component/Subtitle/Subtitlle";
import Testimonial from "@/component/Testimonial/Testimonial";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import { useRef } from "react";
import { BiSolidQuoteAltLeft, BiSolidQuoteAltRight } from "react-icons/bi";
import {
  HiOutlineArrowSmLeft,
  HiOutlineArrowSmRight,
  HiStar,
} from "react-icons/hi";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Autoplay, Navigation } from "swiper/modules";
import { Swiper, SwiperSlide } from "swiper/react";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export default function Home() {
  const swiperRef = useRef(null);
  return (
    <>
      <Head>
        <title>Diama Technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ======Banner======= */}
      <section
        className={styles.mainBanner}
        style={{ backgroundImage: "url(/images/bannerBg.png)" }}
      >
        <div className="container">
          <Swiper
            modules={[Navigation, Autoplay]}
            spaceBetween={30}
            slidesPerView={1}
            pagination={false}
            autoplay={{ delay: 3000 }}
            loop={true}
          >
            <SwiperSlide>
              <div className={styles.bannerContent}>
                <Subtitle text={"We Connect The Digital Dots"} />
                <h1>
                  Your digital journey from <br />
                  <span> Utopia to Eutopia</span>
                </h1>
                <CommonButton text="Our Services" href="/service" />
              </div>
              <div className={styles.bannerImage}>
                <img src={"/images/Connect-the-Dots.jpg"} alt="banner image" />
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={styles.bannerContent}>
                <Subtitle
                  text={"Unlock Limitless Possibilities in the Digital Era"}
                />
                <h1>
                  Your Growth,our mission
                  <span>
                    strategy,technology & creativity in perfect harmony.
                  </span>
                </h1>
                <CommonButton text="Our Services" href="/service" />
              </div>
              <div className={styles.bannerImage}>
                <img src={"/images/banner-image.png"} alt="banner image" />
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={styles.bannerContent}>
                <Subtitle
                  text={
                    "Empowering Startups and SMBs with Smart Digital Solutions"
                  }
                />
                <h1>
                  We are a digital startup for
                  <span> Startups and SMBs</span>
                </h1>
                <CommonButton text="Our Services" href="/services" />
              </div>
              <div className={styles.bannerImage}>
                <img src={"/images/banner-3.png"} alt="banner image" />
              </div>
            </SwiperSlide>
          </Swiper>
        </div>
        <div className={styles.shape}>
          <img src={"/images/bannerShape.png"} alt="shape" />
        </div>
        <div className={styles.shape_two}>
          <img src={"/images/banner_icon.png"} alt="shape" />
        </div>
      </section>

      {/* ========Companies======= */}
      <section className={styles.companies}>
        <div className={styles.clientShape}>
          <img src={"/images/client_shape.png"} alt="shape" />
        </div>
        <div className="container">
          <Subtitle text={"Trusted by over 50,000 companies of all sizes"} />
          <div className={styles.companyWrap}>
            <ul>
              <li>
                <img src={"/images/segement.png"} alt="segemnt" />
              </li>
              <li>
                <img src={"/images/asana.png"} alt="asana" />
              </li>
              <li>
                <img src={"/images/intercom.png"} alt="intercom" />
              </li>
              <li>
                <img src={"/images/zenefits.png"} alt="zenefits" />
              </li>
              <li>
                <img src={"/images/greenhouse.png"} alt="greenhouse" />
              </li>
              <li>
                <img src={"/images/chargebee.png"} alt="chargebee" />
              </li>
              <li>
                <img src={"/images/lattice.png"} alt="lattice" />
              </li>
              <li>
                <img src={"/images/frame.png"} alt="frame" />
              </li>
              <li>
                <img src={"/images/mutiny.png"} alt="mutiny" />
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ======vision and mission====== */}
      <section className={styles.visionMission}>
        <div className={styles.visionMissionShape_one}>
          <img src={"/images/v_shape_one.png"} alt="shape" />
        </div>
        <div className={styles.visionMissionShape_two}>
          <img src={"/images/v_shape_two.png"} alt="shape" />
        </div>
        <div className="container">
          <div className={`${styles.row} row`}>
            <div className="col-lg-6">
              <div className={styles.visionImage}>
                <img src={"/images/vision.png"} alt="vision" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.visionContent}>
                <Subtitle text={"Our Vison"} />
                <p>
                  To empower businesses worldwide with innovative digital
                  solutions that drive growth, fuel creativity, and create
                  meaningful connections—helping them succeed today and shape a
                  smarter, more connected tomorrow.
                </p>
                <span className={styles.visionPoint}>Key vison point:</span>
                <ul>
                  <li>
                    Empower Businesses → Driving sustainable growth and success
                    through digital transformation.
                  </li>
                  <li>
                    Inspire Creativity → Fostering innovation and imaginative
                    solutions that make a difference.
                  </li>
                  <li>
                    Shape a Smarter, Connected Future → Building
                    technology-driven ecosystems that connect people, ideas, and
                    opportunities globally.
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className={`${styles.row} row`}>
            <div className="col-lg-6">
              <div className={styles.visionImage}>
                <img src={"/images/mission.png"} alt="vision" />
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.visionContent}>
                <Subtitle text={"Our Mission"} />
                <p>
                  Our mission is to bridge technology and creativity to deliver
                  impactful digital experiences. We are committed to driving
                  growth through innovation, building trust through
                  transparency, and creating long-lasting value for our clients
                  by turning bold ideas into powerful realities.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.missionShape}>
          <img src={"/images/shape-2.png"} alt="shape" />
        </div>
      </section>

      {/* =====popular services====== */}
      <section className={styles.popularServices}>
        <div className={styles.service_shape}>
          <img src={"/images/banner_icon.png"} alt="shape" />
        </div>
        <div className="container">
          <div className={styles.topHeading}>
            <Subtitle text={"Solutions That Drive Success"} />
            <Heading mainText={"Popular"} highlightText={"Services"} />
            <p>
              Smart, innovative, and result-driven services built to grow your
              business.
            </p>
          </div>
          <div
            className={styles.serviceWrap}
            // style={{ backgroundImage: "url('/images/serviceBg.jpg')" }}
          >
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Digital Marketing</Link>
                </h5>
                <p>
                  Crafting data-driven, creative marketing strategies that
                  connect businesses with their audience, boost visibility, and
                  drive sustainable growth.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>UI/UX Design</Link>
                </h5>
                <p>
                  Designing intuitive, user-friendly, and visually stunning
                  experiences that keep customers engaged and satisfied.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Graphic Design</Link>
                </h5>
                <p>
                  Creating impactful and aesthetically engaging designs that
                  communicate your brand’s message clearly and leave a lasting
                  impression.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>Web Design & Devlopment</Link>
                </h5>
                <p>
                  Building responsive, fast, and visually appealing websites
                  that offer seamless navigation and deliver an exceptional user
                  experience across devices.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>

            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>App Development </Link>
                </h5>
                <p>
                  Developing scalable and user-centric applications that
                  streamline processes, enhance engagement, and provide
                  innovative solutions tailored to business needs.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
            <div className={styles.eachService}>
              <div className={styles.eachServiceContent}>
                <h5>
                  <Link href={"#"}>DevOps</Link>
                </h5>
                <p>
                  Implementing efficient, automated workflows that improve
                  software delivery, ensure system reliability, and accelerate
                  innovation while reducing downtime.
                </p>
              </div>
              <div className={styles.eachServiceImg}>
                <img src={"/images/ui-ux.png"} alt="ui-ux" />
              </div>
              <div className={styles.arrowBtn}>
                <Link href={"#"}>
                  <img src={"/images/arrow.png"} alt="ui-ux" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ======testimonial========= */}
      <Testimonial />

      {/* =========subscribe======== */}
      <section className={styles.startProject}>
        <img
          src={"/images/projectshape1.png"}
          alt="rocket"
          className={styles.projectshape1}
        />
        <img
          src={"/images/projectshape2.png"}
          alt="rocket"
          className={styles.projectshape2}
        />
        <div className="container">
          <div className={styles.projectWrap}>
            <img
              src={"/images/rocket.png"}
              alt="rocket"
              className={styles.projectIcon}
            />
            <Heading
              mainText={"Want to Start"}
              highlightText={"a Project?"}
              className={styles.projectHeading}
            />
            <CommonButton text={"Our Services"} href="/service" />
          </div>
        </div>
      </section>

      {/* ======portfolio======= */}
      <section className={styles.portfolio}>
        <div className="container">
          <Subtitle
            text={"Our Portfolio"}
            className={styles.portfolioSubHeading}
          />
          <div
            className={styles.serviceWrap}
            // style={{ backgroundImage: "url('/images/serviceBg.jpg')" }}
          >
            <Heading
              mainText={"Showcasing Innovation,"}
              highlightText={"Creativity & Impact"}
              className={styles.portfolioHeading}
            />

            <Portfolio />
          </div>
        </div>
      </section>

      {/* =====contact===== */}
      <section
        className={styles.contact}
        // style={{ backgroundImage: "url(/images/map.png)" }}
      >
        <div className="container">
          <div className={styles.contactTopImage}>
            <img src={"/images/contact-map.png"} alt="banner image" />
          </div>
          <div className="row">
            <div className="col-lg-4">
              <div className={styles.contactLeft}>
                <h5>What we’re doing</h5>
                <p>Digital Transformation</p>
                <CommonButton text={"Work With Us"} />
              </div>
            </div>
            <div className="col-lg-8">
              <Counter />
            </div>
          </div>
          <p className={styles.creative}>
            From <img src={"/images/india.png"} alt="banner image" /> with{" "}
            <img src={"/images/love.png"} alt="banner image" /> and creativity.
          </p>
        </div>
      </section>

      {/* ------footer-------- */}
      <Footer />
    </>
  );
}
