import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Service.module.css";
import Header from "@/component/Header/Header";
import Subtitle from "@/component/Subtitle/Subtitlle";
import Link from "next/link";
import CommonButton from "@/component/CommonBtn/CommonBtn";
import Heading from "@/component/Heading/Heading";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper/modules";
import {
  HiOutlineArrowSmLeft,
  HiOutlineArrowSmRight,
  HiStar,
} from "react-icons/hi";
import { useRef } from "react";
import { BiSolidQuoteAltLeft, BiSolidQuoteAltRight } from "react-icons/bi";
import Portfolio from "@/component/Portfolio/Portfolio";
import Footer from "@/component/Footer/Footer";
import Counter from "@/component/Counter/Counter";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export default function OurPortfolio() {
  const swiperRef = useRef(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* ======Banner======= */}
      <section
        className={styles.mainBanner}
        style={{ backgroundImage: "url(/images/bannerBg.png)" }}
      >
        <div className="container">
          <div className={styles.bannerContent}>
            <div className={styles.bannerLeftContent}>
              <Subtitle text={"Work That Drives Business Value"} />
              <h1>
                Strategic design and development tailored to<span> meet business goals.</span>
              </h1>
              <CommonButton text="Start Your Project" href="/" />
            </div>

           
          </div>
        </div>
        <div className={styles.shape}>
          <img src={"/images/bannerShape.png"} alt="shape" />
        </div>
      </section>

      {/* ======technology====== */}
      <section className={styles.techWeUse}>
        <div className="container">
          <div className={styles.topHeader}>
            <h3>Technologies we use</h3>
            <p>
              Get to elevate your business with top-notch IT technology and
              enter the world of digital technology Lorem Ipsum is simply <br />{" "}
              dummy text of the printing and typesetting industry. Lorem
            </p>
          </div>
          <div className={styles.techImg}>
            <img src={"/images/techImg.png"} alt="tech img" />
            <p>Tools shown are used in our projects, not owned bt us.</p>
          </div>
        </div>
      </section>

      {/* =======service===== */}
      <section className={styles.serviceSec}>
        <img
          src={"/images/serviceshape.png"}
          alt="tech img"
          className={styles.serviceFirstShape}
        />
        <img
          src={"/images/serviceshape.png"}
          alt="tech img"
          className={styles.serviceFirstShape2}
        />
        <img
          src={"/images/serviceshape.png"}
          alt="tech img"
          className={styles.serviceFirstShape3}
        />
        <img
          src={"/images/vector.png"}
          alt="tech img"
          className={styles.serviceFirstShape4}
        />
        <div className="container">
          <div className={styles.topHeader}>
            <Heading
              className={styles.serviceHeading}
              mainText={"Shaping Identities That Truly Stand Out"}
            />
            <p>
              We create impactful solutions that combine creativity, technology,
              and strategy to drive your business forward.
            </p>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>Product Design & UX/UI Solutions</h4>
                  <p>
                    We create intuitive and user-focused digital experiences
                    that bring your ideas to life. Our process covers everything
                    from user research, wireframing, and prototyping to
                    usability testing, ensuring designs that are both visually
                    stunning and functionally seamless. We focus on enhancing
                    user satisfaction and engagement while aligning perfectly
                    with your brand’s identity.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/uiux.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>Graphic Design</h4>
                  <p>
                    Our graphic design solutions empower your brand to stand out
                    with creativity and consistency. From logos, brand
                    guidelines, and corporate identities to marketing
                    collaterals and social media creatives, we deliver visually
                    compelling designs that communicate your story effectively.
                    Every design is crafted to make a lasting impact and
                    strengthen your brand presence.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/graphics.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>Digital Marketing</h4>
                  <p>
                    Boost your brand visibility and growth with our tailored
                    digital marketing strategies. We provide services in SEO,
                    social media marketing, paid advertising, content creation,
                    and email campaigns to ensure maximum reach and engagement.
                    Our goal is to drive measurable results by connecting your
                    brand with the right audience at the right time.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/dm.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>App Development</h4>
                  <p>
                    We build scalable, secure, and high-performing applications
                    that transform your business ideas into powerful digital
                    solutions. From native mobile apps to cross-platform
                    solutions, our expert developers ensure functionality,
                    speed, and user-friendly interfaces. Every app is designed
                    to deliver performance, reliability, and an excellent user
                    experience.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/app.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>Web Design & Development</h4>
                  <p>
                    Your website is the face of your brand — and we make it
                    unforgettable. From responsive website design to custom
                    development, we build sites that are visually appealing,
                    fast, and optimized for performance. With a blend of
                    creativity and technology, we deliver websites that attract,
                    engage, and convert visitors into loyal customers.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/web.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.eachService}>
            <div className={`row align-items-center ${styles.serviceRow}`}>
              <div className="col-lg-6">
                <div className={styles.serviceContent}>
                  <h4>DevOps</h4>
                  <p>
                    Streamline development and operations with our DevOps
                    solutions. From continuous integration and deployment
                    (CI/CD) to automated infrastructure and monitoring, we
                    ensure faster delivery, improved collaboration, and scalable
                    performance.
                  </p>
                  <Link href={"#"}>
                    Start Today <HiOutlineArrowSmRight />
                  </Link>
                </div>
              </div>
              <div className="col-lg-6">
                <div className={styles.serviceImg}>
                  <img src={"/images/devops.png"} alt="UI UX" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ========Companies======= */}
      <section className={styles.companies}>
        <div className="container">
          <Subtitle text={"Trusted by over 50,000 companies of all sizes"} />
          <div className={styles.companyWrap}>
            <ul>
              <li>
                <img src={"/images/segement.png"} alt="segemnt" />
              </li>
              <li>
                <img src={"/images/asana.png"} alt="asana" />
              </li>
              <li>
                <img src={"/images/intercom.png"} alt="intercom" />
              </li>
              <li>
                <img src={"/images/zenefits.png"} alt="zenefits" />
              </li>
              <li>
                <img src={"/images/greenhouse.png"} alt="greenhouse" />
              </li>
              <li>
                <img src={"/images/chargebee.png"} alt="chargebee" />
              </li>
              <li>
                <img src={"/images/lattice.png"} alt="lattice" />
              </li>
              <li>
                <img src={"/images/frame.png"} alt="frame" />
              </li>
              <li>
                <img src={"/images/mutiny.png"} alt="mutiny" />
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ========build====== */}
      <section
        className={styles.buildTogether}
        style={{ backgroundImage: "url(/images/buildBg.png)" }}
      >
        <img src={"/images/Union.png"} alt="segemnt" className={styles.buildshape} />
        <div className="container">
          <div className={styles.buildTogetherContent}>
            <Heading
              mainText={"Let’s Build the Future Together"}
              className={styles.buildTogetherHeading}
            />
            <p>
              Ready to transform your ideas into reality? Let’s collaborate and
              craft solutions that drive success.
            </p>
            <CommonButton text={"Let’s Work Together"} />
          </div>
        </div>
      </section>

      {/* ------footer-------- */}
      <Footer />
    </>
  );
}
