name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set Node.js version to 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install
      - run: npm run build --no-lint

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIAMA_TECH }}
          channelId: live
          projectId: diama-tech
